language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: amo@pimpmybook.co.za
  on:
    branch: master
  api_key:
    secure: giS96d0Wrojqn0V5EWtWdBFhsgVgaFEDylABUVOkyX5ZkwwhtsvhP6tos1UZHCzNNBUYsScbvjFKte3wUm53HwRzRkmzLmDsmbYvK9Fpq6DnFfpqPm5C0mq9uLYt2SJc5cVzoS1UIQx1W8oIgac5GH9EXvTcvf2RHZQOrrw0KI02WiJ11j/OvX2Ven4QxmagHrEwZKYX45QFrvfxu8gbNMfBhIv/o/dMGKOBqNJv21SAMKshKl5OXrBHgt+cXmM8p9hQo9H5nCn0yj/DhkgGru8zyIp7eYoKobnupyvk0cKcl7LgNYLZb6SFMlAgOsJ1vviMjrFdjgxuikCJjEHeHhSWGMfkpAmidxI4lMx9jFvufAHQLgvSrh8ucUMkJWL7/ATvOoJJoWOV+sNICj0mWy880vA3JNIqGTYqd6NOO2QIZi0ly+PaowjlTZAIWrWC5O6O87f2RBfC8MFA7LG7VJM9RnMpl2E5n6ZOPtZPgV7EqwbSYavfShFEPVupKZJ5nqMOGXa40OYXFmiB7ShxLMW5wBGzRJKBOLL8hIJi/D74LymSgRuBPUD0cTG1tqDdcrj9MJl+1yGLl1b4ONJ5TKeQeWe3k2tFMv5+vUvyodg/Ui3uxz7lmjW14TqJ4E1mJn538OQb11azmbCxz2ZIJ6oWQmvGY6Eii60M1H5pk3o=
